"""
═══════════════════════════════════════════════════════════════
  AI INFRA AGENT
  
  Two modes:
    python ai_agent.py review  → Explain terraform plan in PR
    python ai_agent.py heal    → Diagnose failures, create issue
═══════════════════════════════════════════════════════════════
"""
import os
import re
import sys
import json
from pathlib import Path
from groq import Groq
from github import Github


# ─── Setup ─────────────────────────────────────────────────────
llm = Groq(api_key=os.environ["GROQ_API_KEY"])
gh = Github(os.environ["GITHUB_TOKEN"])

REPO_NAME = os.environ["REPO_NAME"]
repo = gh.get_repo(REPO_NAME)

MODEL = "llama-3.3-70b-versatile"


# ═══════════════════════════════════════════════════════════════
#   MODE 1: REVIEW — explain terraform plan in plain English
# ═══════════════════════════════════════════════════════════════
def review_plan():
    """Read terraform plan output, ask AI to explain, post to PR."""
    
    plan_file = Path("plan_human.txt")
    if not plan_file.exists():
        print("❌ No plan_human.txt found")
        return
    
    plan_text = plan_file.read_text()
    if len(plan_text) > 8000:
        plan_text = plan_text[:8000] + "\n...(truncated)"
    
    # Extract plan summary numbers
    match = re.search(
        r"Plan:\s+(\d+)\s+to add,\s+(\d+)\s+to change,\s+(\d+)\s+to destroy",
        plan_text
    )
    if match:
        add, change, destroy = int(match.group(1)), int(match.group(2)), int(match.group(3))
    else:
        # "No changes" case
        add = change = destroy = 0
    
    print(f"📊 Plan: +{add} ~{change} -{destroy}")
    
    # Risk assessment
    if destroy > 0:
        risk = "🔴 HIGH — destroys resources"
    elif change > 0:
        risk = "🟡 MEDIUM — modifies existing resources"
    elif add > 0:
        risk = "🟢 LOW — only creates new resources"
    else:
        risk = "⚪ NONE — no changes"
    
    # Ask AI
    prompt = f"""You are a senior DevOps engineer reviewing a Terraform plan.

Plan summary: {add} to add, {change} to change, {destroy} to destroy

Full plan output:
{plan_text}

Explain in this format:

## 📊 Summary
(2 sentences max)

## ✅ Resources Being Created
(bullet list with key properties)

## 🔄 Resources Being Modified
(if any, otherwise write "None")

## ❌ Resources Being Destroyed
(if any, warn clearly; otherwise "None")

## ⚠️ Things to Watch
(security risks, cost, breaking changes)

## 💰 Cost Estimate
(rough monthly cost)

## 🎚️ Confidence
(low/medium/high + reason)

Be specific. Reference actual resource names."""
    
    print("🧠 Asking AI...")
    response = llm.chat.completions.create(
        model=MODEL,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.2,
        max_tokens=1500,
    )
    explanation = response.choices[0].message.content
    
    # Build the comment
    comment = f"""# 🤖 AI Terraform Plan Review

**Plan:** ✅ {add} to add · 🔄 {change} to change · ❌ {destroy} to destroy
**Risk Level:** {risk}

---

{explanation}

---

_Generated by AI Plan Reviewer · Always sanity-check before applying!_
"""
    
    # Post to step summary (always visible)
    summary_file = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary_file:
        with open(summary_file, "a") as f:
            f.write(comment)
        print("✅ Posted to GitHub step summary")
    
    # Post to PR if applicable
    pr_number = os.environ.get("PR_NUMBER", "")
    if pr_number:
        try:
            pr = repo.get_pull(int(pr_number))
            pr.create_issue_comment(comment)
            print(f"✅ Posted to PR #{pr_number}")
        except Exception as e:
            print(f"Couldn't post to PR: {e}")


# ═══════════════════════════════════════════════════════════════
#   MODE 2: HEAL — diagnose pipeline failure
# ═══════════════════════════════════════════════════════════════
def heal_failure():
    """Get failure context, ask AI to diagnose, create GitHub issue."""
    
    run_id = int(os.environ["RUN_ID"])
    run = repo.get_workflow_run(run_id)
    
    print(f"🩺 Healing run #{run.run_number}")
    
    # Get failed jobs
    failed = []
    for job in run.jobs():
        if job.conclusion == "failure":
            failed_steps = [s.name for s in job.steps if s.conclusion == "failure"]
            failed.append({
                "job_name": job.name,
                "failed_steps": failed_steps,
                "url": job.html_url,
            })
    
    if not failed:
        print("No failed jobs found")
        return
    
    print(f"  Failed: {[j['job_name'] for j in failed]}")
    
    # Get terraform & workflow files
    files = {}
    for path in ["main.tf", ".github/workflows/ai-agent.yml"]:
        try:
            content = repo.get_contents(path).decoded_content.decode()
            files[path] = content[:2500]
        except Exception as e:
            print(f"  Couldn't read {path}: {e}")
    
    # Ask AI
    prompt = f"""You are a Terraform + AWS expert. A Terraform deploy failed in GitHub Actions.

Failed jobs:
{json.dumps(failed, indent=2)}

Project files:
{json.dumps(files, indent=2)[:5000]}

Workflow URL: {run.html_url}

Common causes to consider:
1. IAM user lacks permissions (EC2, VPC, etc.)
2. Resource name conflict (already exists)
3. AWS service quotas/limits hit
4. Invalid AMI for region
5. AWS region misconfigured
6. Provider version conflicts
7. Default VPC missing (rare)
8. Wrong syntax in main.tf

Respond in this exact markdown format:

## 🎯 Root Cause
(one specific sentence)

## 📍 Where
(file:line or "GitHub Actions job: X")

## 💡 Why This Happened
(2-3 sentences)

## 🔧 Suggested Fix
```diff
- old
+ new
```
OR
```bash
# AWS CLI commands if it's a setup issue
```

## 🧪 How to Verify
(steps)

## 🎚️ Confidence
(percentage + reason)
"""
    
    print("🧠 Asking AI for diagnosis...")
    response = llm.chat.completions.create(
        model=MODEL,
        messages=[{"role": "user", "content": prompt}],
        temperature=0.2,
        max_tokens=1500,
    )
    diagnosis = response.choices[0].message.content
    
    # Create issue
    title = f"🤖 AI Diagnosis: Terraform failed (run #{run.run_number})"
    body = f"""## Terraform Deployment Failure

**Workflow:** [{run.name}]({run.html_url})
**Commit:** {run.head_sha[:7]}
**Failed jobs:** {', '.join(j['job_name'] for j in failed)}

---

{diagnosis}

---

### 🛟 Quick Recovery

If state is locked:
```bash
terraform force-unlock <LOCK_ID>
```

To retry from local:
```bash
terraform init
terraform plan
terraform apply
```

_🤖 AI Healer · Add label `ai-wrong` if diagnosis is incorrect_
"""
    
    issue = repo.create_issue(
        title=title,
        body=body,
        labels=["ai-diagnosis", "terraform", "ci-failure"],
    )
    print(f"✅ Issue created: {issue.html_url}")


# ═══════════════════════════════════════════════════════════════
#   ROUTER
# ═══════════════════════════════════════════════════════════════
if __name__ == "__main__":
    mode = sys.argv[1] if len(sys.argv) > 1 else ""
    
    if mode == "review":
        review_plan()
    elif mode == "heal":
        heal_failure()
    else:
        print("Usage: python ai_agent.py [review|heal]")
        sys.exit(1)
